In [1]:
import pandas as pd
df = pd.read_csv("diminos_data.csv")
df.head()

   order_id      order_placed_at          order_delivered_at
0   1523111  2023-03-01 00:00:59  2023-03-01 00:18:07.443132
1   1523112  2023-03-01 00:03:59  2023-03-01 00:19:34.925241
2   1523113  2023-03-01 00:07:22  2023-03-01 00:22:28.291385
3   1523114  2023-03-01 00:07:47  2023-03-01 00:46:19.019399
4   1523115  2023-03-01 00:09:03  2023-03-01 00:25:13.619056

In [3]:
df["order_placed_at"] = pd.to_datetime(df["order_placed_at"])
df["order_delivered_at"] = pd.to_datetime(df["order_delivered_at"])
df["delivery_minutes"] = (df["order_delivered_at"] - df["order_placed_at"]).dt.total_seconds() / 60
df.head()

   order_id     order_placed_at         order_delivered_at  delivery_minutes
0   1523111 2023-03-01 00:00:59 2023-03-01 00:18:07.443132         17.140719
1   1523112 2023-03-01 00:03:59 2023-03-01 00:19:34.925241         15.598754
2   1523113 2023-03-01 00:07:22 2023-03-01 00:22:28.291385         15.104856
3   1523114 2023-03-01 00:07:47 2023-03-01 00:46:19.019399         38.533657
4   1523115 2023-03-01 00:09:03 2023-03-01 00:25:13.619056         16.176984

In [4]:
df["delivery_minutes"].describe()

count    15000.000000
mean        20.499389
std         96.160362
min         15.000010
25%         15.274826
50%         15.797986
75%         17.279661
max       7299.831375
Name: delivery_minutes, dtype: float64

In [23]:
delayed_orders = df[df["delivery_minutes"] > 45]
delayed_orders
delay_percentage = (len(delayed_orders) / len(df)) * 100
delay_percentage

1.7466666666666666

In [7]:
df["order_hour"] = df["order_placed_at"].dt.hour
orders_by_hour = df["order_hour"].value_counts().sort_index()
orders_by_hour

order_hour
0     621
1     610
2     610
3     629
4     633
5     641
6     658
7     559
8     603
9     634
10    627
11    655
12    625
13    622
14    631
15    602
16    597
17    617
18    636
19    636
20    590
21    636
22    655
23    673
Name: count, dtype: int64

In [15]:
orders_by_hour.idxmax(), orders_by_hour.max()

(np.int32(23), np.int64(673))

In [16]:
orders_by_hour.idxmin(), orders_by_hour.min()

(np.int32(7), np.int64(559))

In [18]:
avg_delivery_by_hour = df.groupby("order_hour")["delivery_minutes"].mean()
avg_delivery_by_hour

order_hour
0     24.116781
1     20.836201
2     19.123197
3     19.846034
4     18.818769
5     17.727910
6     18.501060
7     18.368406
8     19.264601
9     33.320277
10    21.014310
11    25.908233
12    19.731810
13    18.403554
14    18.999574
15    17.619334
16    18.711819
17    30.352864
18    17.758926
19    18.253996
20    19.247353
21    18.263140
22    18.963806
23    18.544586
Name: delivery_minutes, dtype: float64

In [19]:
sla_20 = (df["delivery_minutes"] <= 20).mean() * 100
sla_30 = (df["delivery_minutes"] <= 30).mean() * 100
sla_20, sla_30

(np.float64(87.78), np.float64(95.97333333333333))